/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'

const AdminLazyRouteImport = createFileRoute('/admin')()
const IndexLazyRouteImport = createFileRoute('/')()
const InvitationTokenLazyRouteImport = createFileRoute('/invitation/$token')()
const DrawingsDeletedLazyRouteImport = createFileRoute('/drawings/deleted')()

const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const InvitationTokenLazyRoute = InvitationTokenLazyRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/invitation/$token.lazy').then((d) => d.Route),
)
const DrawingsDeletedLazyRoute = DrawingsDeletedLazyRouteImport.update({
  id: '/drawings/deleted',
  path: '/drawings/deleted',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/drawings/deleted.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLazyRoute
  '/drawings/deleted': typeof DrawingsDeletedLazyRoute
  '/invitation/$token': typeof InvitationTokenLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLazyRoute
  '/drawings/deleted': typeof DrawingsDeletedLazyRoute
  '/invitation/$token': typeof InvitationTokenLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLazyRoute
  '/drawings/deleted': typeof DrawingsDeletedLazyRoute
  '/invitation/$token': typeof InvitationTokenLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/drawings/deleted'
    | '/invitation/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/drawings/deleted'
    | '/invitation/$token'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/drawings/deleted'
    | '/invitation/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminLazyRoute: typeof AdminLazyRoute
  DrawingsDeletedLazyRoute: typeof DrawingsDeletedLazyRoute
  InvitationTokenLazyRoute: typeof InvitationTokenLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/deleted': {
      id: '/drawings/deleted'
      path: '/drawings/deleted'
      fullPath: '/drawings/deleted'
      preLoaderRoute: typeof DrawingsDeletedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminLazyRoute: AdminLazyRoute,
  DrawingsDeletedLazyRoute: DrawingsDeletedLazyRoute,
  InvitationTokenLazyRoute: InvitationTokenLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
