/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'

const AdminLazyRouteImport = createFileRoute('/admin')()
const AccountLazyRouteImport = createFileRoute('/account')()
const IndexLazyRouteImport = createFileRoute('/')()
const InvitationTokenLazyRouteImport = createFileRoute('/invitation/$token')()
const DrawingsDeletedLazyRouteImport = createFileRoute('/drawings/deleted')()
const AdminUsersUsernameLazyRouteImport = createFileRoute(
  '/admin/users/$username',
)()
const AdminUsersUsernameDocumentsDocumentIdLazyRouteImport = createFileRoute(
  '/admin/users/$username/documents/$documentId',
)()

const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const AccountLazyRoute = AccountLazyRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const InvitationTokenLazyRoute = InvitationTokenLazyRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/invitation/$token.lazy').then((d) => d.Route),
)
const DrawingsDeletedLazyRoute = DrawingsDeletedLazyRouteImport.update({
  id: '/drawings/deleted',
  path: '/drawings/deleted',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/drawings/deleted.lazy').then((d) => d.Route),
)
const AdminUsersUsernameLazyRoute = AdminUsersUsernameLazyRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/users/$username.lazy').then((d) => d.Route),
)
const AdminUsersUsernameDocumentsDocumentIdLazyRoute =
  AdminUsersUsernameDocumentsDocumentIdLazyRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AdminUsersUsernameLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin/users/$username/documents/$documentId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AccountLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/drawings/deleted': typeof DrawingsDeletedLazyRoute
  '/invitation/$token': typeof InvitationTokenLazyRoute
  '/admin/users/$username': typeof AdminUsersUsernameLazyRouteWithChildren
  '/admin/users/$username/documents/$documentId': typeof AdminUsersUsernameDocumentsDocumentIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AccountLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/drawings/deleted': typeof DrawingsDeletedLazyRoute
  '/invitation/$token': typeof InvitationTokenLazyRoute
  '/admin/users/$username': typeof AdminUsersUsernameLazyRouteWithChildren
  '/admin/users/$username/documents/$documentId': typeof AdminUsersUsernameDocumentsDocumentIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AccountLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/drawings/deleted': typeof DrawingsDeletedLazyRoute
  '/invitation/$token': typeof InvitationTokenLazyRoute
  '/admin/users/$username': typeof AdminUsersUsernameLazyRouteWithChildren
  '/admin/users/$username/documents/$documentId': typeof AdminUsersUsernameDocumentsDocumentIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/account'
    | '/admin'
    | '/drawings/deleted'
    | '/invitation/$token'
    | '/admin/users/$username'
    | '/admin/users/$username/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/account'
    | '/admin'
    | '/drawings/deleted'
    | '/invitation/$token'
    | '/admin/users/$username'
    | '/admin/users/$username/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/account'
    | '/admin'
    | '/drawings/deleted'
    | '/invitation/$token'
    | '/admin/users/$username'
    | '/admin/users/$username/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountLazyRoute: typeof AccountLazyRoute
  AdminLazyRoute: typeof AdminLazyRouteWithChildren
  DrawingsDeletedLazyRoute: typeof DrawingsDeletedLazyRoute
  InvitationTokenLazyRoute: typeof InvitationTokenLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings/deleted': {
      id: '/drawings/deleted'
      path: '/drawings/deleted'
      fullPath: '/drawings/deleted'
      preLoaderRoute: typeof DrawingsDeletedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$username': {
      id: '/admin/users/$username'
      path: '/users/$username'
      fullPath: '/admin/users/$username'
      preLoaderRoute: typeof AdminUsersUsernameLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/users/$username/documents/$documentId': {
      id: '/admin/users/$username/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/admin/users/$username/documents/$documentId'
      preLoaderRoute: typeof AdminUsersUsernameDocumentsDocumentIdLazyRouteImport
      parentRoute: typeof AdminUsersUsernameLazyRoute
    }
  }
}

interface AdminUsersUsernameLazyRouteChildren {
  AdminUsersUsernameDocumentsDocumentIdLazyRoute: typeof AdminUsersUsernameDocumentsDocumentIdLazyRoute
}

const AdminUsersUsernameLazyRouteChildren: AdminUsersUsernameLazyRouteChildren =
  {
    AdminUsersUsernameDocumentsDocumentIdLazyRoute:
      AdminUsersUsernameDocumentsDocumentIdLazyRoute,
  }

const AdminUsersUsernameLazyRouteWithChildren =
  AdminUsersUsernameLazyRoute._addFileChildren(
    AdminUsersUsernameLazyRouteChildren,
  )

interface AdminLazyRouteChildren {
  AdminUsersUsernameLazyRoute: typeof AdminUsersUsernameLazyRouteWithChildren
}

const AdminLazyRouteChildren: AdminLazyRouteChildren = {
  AdminUsersUsernameLazyRoute: AdminUsersUsernameLazyRouteWithChildren,
}

const AdminLazyRouteWithChildren = AdminLazyRoute._addFileChildren(
  AdminLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountLazyRoute: AccountLazyRoute,
  AdminLazyRoute: AdminLazyRouteWithChildren,
  DrawingsDeletedLazyRoute: DrawingsDeletedLazyRoute,
  InvitationTokenLazyRoute: InvitationTokenLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
