import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const splatterboardDir = resolve(scriptDir, "..");
const assetsRootDir = resolve(splatterboardDir, "src", "coloring", "assets");
const outputFilePath = resolve(
  splatterboardDir,
  "src",
  "coloring",
  "generatedColoringPageAssets.ts",
);

type VolumeConfig = {
  volumeId: "pdr-v1" | "pdr-v2";
  volumeLabel: string;
  folderName: string;
  importPrefix: "v1" | "v2";
};

const VOLUMES: readonly VolumeConfig[] = [
  {
    volumeId: "pdr-v1",
    volumeLabel: "PDR Volume 1",
    folderName: "pdr-v1",
    importPrefix: "v1",
  },
  {
    volumeId: "pdr-v2",
    volumeLabel: "PDR Volume 2",
    folderName: "pdr-v2",
    importPrefix: "v2",
  },
] as const;

type GeneratedEntry = {
  id: string;
  volumeId: "pdr-v1" | "pdr-v2";
  volumeLabel: string;
  pageNumber: number;
  width: number;
  height: number;
  importName: string;
  importPath: string;
};

function getPageNumber(filename: string): number | null {
  const match = /^page-(\d{3})\.png$/.exec(filename);
  if (!match) {
    return null;
  }
  return Number.parseInt(match[1], 10);
}

function getPngSize(filePath: string): { width: number; height: number } {
  const buffer = readFileSync(filePath);
  // PNG signature (8 bytes) + IHDR chunk length/type (8 bytes) + IHDR data starts at byte 16.
  const signature = "89504e470d0a1a0a";
  if (
    buffer.length < 24 ||
    buffer.subarray(0, 8).toString("hex") !== signature
  ) {
    throw new Error(`Not a valid PNG file: ${filePath}`);
  }
  const width = buffer.readUInt32BE(16);
  const height = buffer.readUInt32BE(20);
  return { width, height };
}

const entries: GeneratedEntry[] = [];

for (const volume of VOLUMES) {
  const volumeDir = resolve(assetsRootDir, volume.folderName);
  const pageFiles = readdirSync(volumeDir)
    .filter((filename) => getPageNumber(filename) !== null)
    .sort((a, b) => a.localeCompare(b));

  for (const pageFile of pageFiles) {
    const pageNumber = getPageNumber(pageFile);
    if (pageNumber === null) {
      continue;
    }
    const page = String(pageNumber).padStart(3, "0");
    const importName = `${volume.importPrefix}_page_${page}`;
    const size = getPngSize(resolve(volumeDir, pageFile));
    entries.push({
      id: `${volume.volumeId}-${page}`,
      volumeId: volume.volumeId,
      volumeLabel: volume.volumeLabel,
      pageNumber,
      width: size.width,
      height: size.height,
      importName,
      importPath: `./assets/${volume.folderName}/${pageFile}`,
    });
  }
}

const header = `/* eslint-disable */\n// Generated by scripts/generate-coloring-assets.ts\nexport interface GeneratedColoringAsset {\n  id: string;\n  volumeId: "pdr-v1" | "pdr-v2";\n  volumeLabel: string;\n  pageNumber: number;\n  width: number;\n  height: number;\n  src: string;\n}\n\n`;

const imports = entries
  .map((entry) => `import ${entry.importName} from '${entry.importPath}';`)
  .join("\n");

const assets = entries
  .map(
    (entry) =>
      `  { id: '${entry.id}', volumeId: '${entry.volumeId}', volumeLabel: '${entry.volumeLabel}', pageNumber: ${entry.pageNumber}, width: ${entry.width}, height: ${entry.height}, src: ${entry.importName} },`,
  )
  .join("\n");

const output = `${header}${imports}\n\nexport const GENERATED_COLORING_ASSETS: readonly GeneratedColoringAsset[] = [\n${assets}\n] as const;\n`;

writeFileSync(outputFilePath, output, "utf8");
console.log(`Wrote ${entries.length} coloring assets to ${outputFilePath}`);
