import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const splatDir = resolve(scriptDir, "..");
const assetsRootDir = resolve(splatDir, "src", "coloring", "assets");
const booksRootDir = resolve(splatDir, "src", "coloring", "books");
const outputFilePath = resolve(
  splatDir,
  "src",
  "coloring",
  "generatedColoringPageAssets.ts",
);

type BookManifest = {
  slug: string;
  title: string;
  url: string | null;
};

type GeneratedEntry = {
  id: string;
  volumeId: string;
  volumeLabel: string;
  sourceUrl: string | null;
  pageNumber: number;
  width: number;
  height: number;
  importName: string;
  importPath: string;
};

function getPageNumber(filename: string): number | null {
  const match = /^page-(\d{3})\.png$/.exec(filename);
  if (!match) {
    return null;
  }
  return Number.parseInt(match[1], 10);
}

function getPngSize(filePath: string): { width: number; height: number } {
  const buffer = readFileSync(filePath);
  const signature = "89504e470d0a1a0a";
  if (
    buffer.length < 24 ||
    buffer.subarray(0, 8).toString("hex") !== signature
  ) {
    throw new Error(`Not a valid PNG file: ${filePath}`);
  }
  const width = buffer.readUInt32BE(16);
  const height = buffer.readUInt32BE(20);
  return { width, height };
}

function toImportIdentifier(input: string): string {
  const normalized = input.replace(/[^a-zA-Z0-9_]/g, "_");
  if (/^[0-9]/.test(normalized)) {
    return `book_${normalized}`;
  }
  return normalized;
}

const manifestFiles = readdirSync(booksRootDir)
  .filter((name) => extname(name) === ".json")
  .sort((a, b) => a.localeCompare(b));

const entries: GeneratedEntry[] = [];

for (const manifestFile of manifestFiles) {
  const manifestPath = resolve(booksRootDir, manifestFile);
  const manifest = JSON.parse(
    readFileSync(manifestPath, "utf8"),
  ) as BookManifest;

  if (!manifest.slug || !manifest.title) {
    throw new Error(`Invalid book manifest: ${manifestPath}`);
  }

  const volumeDir = resolve(assetsRootDir, manifest.slug);
  const pageFiles = readdirSync(volumeDir)
    .filter((filename) => getPageNumber(filename) !== null)
    .sort((a, b) => a.localeCompare(b));

  const importPrefix = toImportIdentifier(manifest.slug);
  for (const pageFile of pageFiles) {
    const pageNumber = getPageNumber(pageFile);
    if (pageNumber === null) {
      continue;
    }
    const page = String(pageNumber).padStart(3, "0");
    const importName = `${importPrefix}_page_${page}`;
    const size = getPngSize(resolve(volumeDir, pageFile));
    entries.push({
      id: `${manifest.slug}-${page}`,
      volumeId: manifest.slug,
      volumeLabel: manifest.title,
      sourceUrl: manifest.url,
      pageNumber,
      width: size.width,
      height: size.height,
      importName,
      importPath: `./assets/${manifest.slug}/${pageFile}`,
    });
  }
}

const header = `/* eslint-disable */\n// Generated by scripts/generate-coloring-assets.ts\nexport interface GeneratedColoringAsset {\n  id: string;\n  volumeId: string;\n  volumeLabel: string;\n  sourceUrl: string | null;\n  pageNumber: number;\n  width: number;\n  height: number;\n  src: string;\n}\n\n`;

const imports = entries
  .map((entry) => `import ${entry.importName} from '${entry.importPath}';`)
  .join("\n");

const assets = entries
  .map((entry) => {
    const sourceUrl =
      entry.sourceUrl === null
        ? "null"
        : `'${entry.sourceUrl.replaceAll("'", "\\'")}'`;
    return `  { id: '${entry.id}', volumeId: '${entry.volumeId}', volumeLabel: '${entry.volumeLabel}', sourceUrl: ${sourceUrl}, pageNumber: ${entry.pageNumber}, width: ${entry.width}, height: ${entry.height}, src: ${entry.importName} },`;
  })
  .join("\n");

const output = `${header}${imports}\n\nexport const GENERATED_COLORING_ASSETS: readonly GeneratedColoringAsset[] = [\n${assets}\n] as const;\n`;

writeFileSync(outputFilePath, output, "utf8");
console.log(`Wrote ${entries.length} coloring assets to ${outputFilePath}`);
